# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  action_mailer_user_name: <%= ENV["ACTION_MAILER_UESR_NAME"] %>
  action_mailer_password: <%= ENV["ACTION_MAILER_PASSWORD"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  google_map_api_key: <%= ENV["GOOGLE_MAP_API_KEY"] %>
  mail_host: <%= ENV["MAIL_HOST"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>

review_app:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  google_map_api_key: <%= ENV["GOOGLE_MAP_API_KEY"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_fog_directory: <%= ENV["AWS_FOG_DIRECTORY"] %>
  aws_s3_region: <%= ENV["AWS_S3_REGION"] %>
  aws_s3_bucket: <%= ENV["AWS_S3_BUCKET"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  google_map_api_key: <%= ENV["GOOGLE_MAP_API_KEY"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_fog_directory: <%= ENV["AWS_FOG_DIRECTORY"] %>
  aws_s3_region: <%= ENV["AWS_S3_REGION"] %>
  aws_s3_bucket: <%= ENV["AWS_S3_BUCKET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  google_map_api_key: <%= ENV["GOOGLE_MAP_API_KEY"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_fog_directory: <%= ENV["AWS_FOG_DIRECTORY"] %>
  aws_s3_region: <%= ENV["AWS_S3_REGION"] %>
  aws_s3_bucket: <%= ENV["AWS_S3_BUCKET"] %>
